global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['backend:4000']

  - job_name: 'kong'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['kong:8001']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'kratos'
    metrics_path: '/metrics/prometheus'
    static_configs:
      - targets: ['kratos:4434']

  - job_name: 'opa'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['opa:8181']

  - job_name: 'frontend'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['frontend:3000']
